# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  ports:
    default: 9000
    description: http port where minio server is available.
    type: int
  username:
    default: minio
    description: Username to be passed alongwith the server to access the same.
    type: string
  password:
    default: NULL
    description: Password to be passed alongwith the server to access the same.
    type: string
